### ISSUE TITLE
Make GoState hash computation parallel

### ISSUE THREAD

**Issue by hkalina** [Fantom-foundation/Carmen#265]
As the run-vm (go-file) consumes **7.7%** of runVM time in the `GoState.GetHash` function, maybe we can speed it up by computing the hash of individual stores and indexes in parallel.

The time consumed in individual stores/indexes hashing:
* addressIndex - 24 ms
* keyIndex - 2068 ms
* slotIndex - 1350 ms
* balancesStore - **12286 ms** (13%)
* noncesStore - 9173 ms (9%)
* valuesStore - **70986 ms** (73%)
* accountsStore - 813 ms
* codesDepot - 269 ms

Measured in build: https://team.fantom.network/buildConfiguration/Aida_RunVm/1632 (to block 6M)

Without parallelization of one store hashing, the maximal time saving is **27%** of the hashing time, the critical path is the valuesStore, which consumes 73% of the hashing time.

**Comment by HerbertJordan** [comment]
This has been attempted several times, but so far, the synchronization overhead of distributing the workload to multiple go-routines and coordinating disk and node-cache accesses was not sufficiently compensated by the parallel execution. Every attempt -- so far -- resulted in a slow-down.

In part, this is due to the small block sizes (only a few transactions performing a small number of MPT updates), and the resulting short time for processing a single block when syncing a node. Each block takes only a few milliseconds. In this short time scales, distributing and merging concurrent tasks is difficult.
