### ISSUE TITLE
Expose account storage root in API

### ISSUE THREAD

**Issue by thaarok** [Fantom-foundation/Carmen#887]
StateDB (and so even Carmen facade) should provide `GetStorageRoot(address)` method to obtain the storage root of an account.

There are two use cases:
* checking if the storage of the account is empty during a contract deployment (only compared with `EmptyRootHash`)
  * Necessary for the go-ethereum upgrade, required by EIP-7610: https://github.com/ethereum/go-ethereum/pull/28912
* part of the witness proof - returned as part of `eth_getProof` output
  * (this may be already part of the witness proof integration?)

**Comment by HerbertJordan** [comment]
Based on the requirements, I would argue that a `HasEmptyStorage(Address)` function would be sufficient.

The use of the storage hash in the proof is implicit anyway, no need to expose it in the facade.

**Comment by HerbertJordan** [comment]
Alternative name: `IsStorageEmpty(Address)`

**Comment by petr-hanzl** [comment]
This is not necessary for now since the need for implementing HasEmptyStorage has been proven as not needed anymore.
Investigation done by @HerbertJordan summarized in this https://github.com/Fantom-foundation/Carmen/pull/924#issuecomment-2180337715 revealed that this code would not actually be used.

**Solution for sonic would be to always return a non-hash.**
